import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import React from "react";
import { useRecoilValue } from "recoil";
import { countState } from "../atoms";

export default function Home() {
	// recoil
	const count = useRecoilValue<number>(countState);
	// useEffectで初回起動時のみclassを付与してスプラッシュを実現させたい
	// useEffect(
	// 	() => {
	// 		// 初回レンダリング後に実行されるため、
	// 		// refは今このタイミングで設定される
	// 		console.log("render");
	// 		// inputRef.current.focus();
	// 	},
	// 	// 副作用はinputRefに依存する
	// 	[inputRef]
	// );
	return (
		<div className={styles.container}>
			<Head>
				<title>webviwe</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h3>count : {count}</h3>
				<Link href="/button">
					<a>To button page</a>
				</Link>
			</main>
		</div>
	);
}
